### ISSUE TITLE
Recursive dryrun is "silent"

### ISSUE THREAD

**Issue by automatonic** [dylansmith/node-exif-renamer#3]
I have tested `exif-renamer` on several directories so far, trying to narrow down to a successful directory/batch. Unfortunately, the tool does not produce any output until completion/exception. If there are any `-d` renames that did succeed, then I can't tell from the output. *Please consider more proactive output.* 

When i run this on my 30K file directory, the process just "hangs" with no output. presumably it is still working, but all the predicted renames are held to the end?

**Comment by automatonic** [comment]
I will try and dig in further this evening. `exif-renamer` has what i want in terms of features, if I can just get over a couple hurdles. I will see if I can't build up a couple pull requests to help out. My test set is large, unwieldy, and very "real world" :smile:

**Comment by automatonic** [comment]
oh, and thanks for building this in the first place. your efforts are very much appreciated.

**Comment by dylansmith** [comment]
In progress.

**Comment by dylansmith** [comment]
Hey, can you take a look at https://github.com/dylansmith/node-exif-renamer/tree/replace-exif-parser? It contains updates which may solve some or all of your problems. Don't forget to run `npm install` after checking out the code, and run `bin/exif-renamer <ARGS>` otherwise your shell will continue to use the older global version.

**Comment by automatonic** [comment]
@dylansmith excellent, thanks. Unfortunately npm is now broken on my diskstation (where i am running my renames) So the install/update fails with `ENOGIT`. I will try to get that sorted out and retry (even if i have to just xcopy the .js files down.)

Thanks for your support in this!

**Comment by dylansmith** [comment]
Hey @automatonic, no problem. Thanks for your feedback - it has made the project better.

The `ENOGIT` error means that you don't have git installed on that machine. The reason that is now required is because I am waiting for my [pull request](https://github.com/bwindels/exif-parser/pull/5) to fix the date parsing to be merged into the module that I'm using for EXIF parsing. Until then, I have to point that dependency at my own fork of the repo, and hence npm requires git to be installed so that it can fetch the code. If you are interested, see the `exif-parser` dependency in my [package.json](https://github.com/dylansmith/node-exif-renamer/blob/master/package.json#L44).

**Comment by automatonic** [comment]
Ah...that explains why the limited npm install on my synology diskstation worked initially, but now is failing. The `ENOGIT` was clear enough with some googling, but it was less clear why it had worked and then stopped. Thanks for the explanation.
